---
Name: silverware-social
---

# Configure Page Extensions:

Page:
  extensions:
    - SilverWare\Social\Extensions\PageExtension

# Configure Content Controller:

SilverStripe\CMS\Controllers\ContentController:
  required_js:
    - "silverware/social: client/dist/js/bundle.js"
  required_css:
    - "silverware/social: client/dist/styles/bundle.css"
